# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: index.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='index.proto',
  package='index',
  syntax='proto3',
  serialized_pb=_b('\n\x0bindex.proto\x12\x05index\"1\n\x10IndexPostRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x03\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x1e\n\x0eIndexPostReply\x12\x0c\n\x04text\x18\x01 \x01(\t2D\n\x07Indexer\x12\x39\n\x05index\x12\x17.index.IndexPostRequest\x1a\x15.index.IndexPostReply\"\x00\x62\x06proto3')
)




_INDEXPOSTREQUEST = _descriptor.Descriptor(
  name='IndexPostRequest',
  full_name='index.IndexPostRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='post_id', full_name='index.IndexPostRequest.post_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='index.IndexPostRequest.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=71,
)


_INDEXPOSTREPLY = _descriptor.Descriptor(
  name='IndexPostReply',
  full_name='index.IndexPostReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='index.IndexPostReply.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['IndexPostRequest'] = _INDEXPOSTREQUEST
DESCRIPTOR.message_types_by_name['IndexPostReply'] = _INDEXPOSTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IndexPostRequest = _reflection.GeneratedProtocolMessageType('IndexPostRequest', (_message.Message,), dict(
  DESCRIPTOR = _INDEXPOSTREQUEST,
  __module__ = 'index_pb2'
  # @@protoc_insertion_point(class_scope:index.IndexPostRequest)
  ))
_sym_db.RegisterMessage(IndexPostRequest)

IndexPostReply = _reflection.GeneratedProtocolMessageType('IndexPostReply', (_message.Message,), dict(
  DESCRIPTOR = _INDEXPOSTREPLY,
  __module__ = 'index_pb2'
  # @@protoc_insertion_point(class_scope:index.IndexPostReply)
  ))
_sym_db.RegisterMessage(IndexPostReply)



_INDEXER = _descriptor.ServiceDescriptor(
  name='Indexer',
  full_name='index.Indexer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=105,
  serialized_end=173,
  methods=[
  _descriptor.MethodDescriptor(
    name='index',
    full_name='index.Indexer.index',
    index=0,
    containing_service=None,
    input_type=_INDEXPOSTREQUEST,
    output_type=_INDEXPOSTREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INDEXER)

DESCRIPTOR.services_by_name['Indexer'] = _INDEXER

# @@protoc_insertion_point(module_scope)
