# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import search_pb2 as search__pb2


class SearchStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.search = channel.unary_unary(
        '/index.Search/search',
        request_serializer=search__pb2.SearchRequest.SerializeToString,
        response_deserializer=search__pb2.SearchReply.FromString,
        )


class SearchServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def search(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SearchServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'search': grpc.unary_unary_rpc_method_handler(
          servicer.search,
          request_deserializer=search__pb2.SearchRequest.FromString,
          response_serializer=search__pb2.SearchReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'index.Search', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
